---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/customers/nearby":
    post:
      summary: Upload customers file and filter by 100km radius
      parameters: []
      responses:
        '200':
          description: customers found
        '400':
          description: bad request
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
        required: true
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
